config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  resources :text_messages, only: :create

  root 'welcome#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/text_messages_controller.rb
# frozen_string_literal: true

class TextMessagesController < ApplicationController
  # rescue_from StandardError, with: :render_error # TODO: rescue from more specific errors

  def create
    spotify_client = SpotifyClient.new(params[:artist])
    body = "#{spotify_client.artist.name}'s top track: #{spotify_client.top_track.name}"
    message = send_message(body)
    render json: { to: message.to, message: message.body, artist_info: spotify_client.artist_info }
  end

  private

  # def text_message_params
  #   binding.pry
  #   params.permit(:artist, :phone_number)
  # end

  def send_message(body)
    twilio_client = TwilioClient.new
    twilio_client.send_text(params[:phone_number], body)
  end

  def render_error
    render json: { message: 'Woops. Something went wrong.' }, status: :internal_server_error
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %title DemoTape
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    %script{defer: "defer", src: "https://use.fontawesome.com/releases/v5.3.1/js/all.js"}
  - data_actions = 'ajax:success->artist-info#populate ajax:error->artist-info#hide'
  %body{data: {controller: 'alerts artist-info', action: data_actions}}
    = yield

app/views/welcome/_alert_box.html.haml
.box.is-invisible{data: {target: 'alerts.alertBox'}}
  %article.media
    .media-content
      .content
        %p
          %strong{data: {target: 'alerts.alertTitle'}}
        %div{data: {target: 'alerts.alertBody'}}

app/views/welcome/_artist_info.html.haml
%article#artist-info-tile.tile.is-child.box
  .columns.is-desktop
    .column.is-one-quarter
      %figure.image.is-96x96
        %img{src: '', data: {target: 'artist-info.image'}}
    .column
      %p.title{data: {target: 'artist-info.name'}}
      %p.subtitle Artist
  .content
    %strong Followers:
    %span{data: {target: 'artist-info.followers'}}

app/views/welcome/_form.html.haml
- data_actions = 'ajax:success->alerts#handleSuccess ajax:error->alerts#handleError'

= form_with url: text_messages_path, data: {action: data_actions} do |form|
  .field
    = form.label :artist, class: :label
    %p.control.has-icons-left.has-icons-right
      = form.text_field(:artist,
                        id: :artist,
                        class: :input,
                        placeholder: 'Queens of the Stone Age',
                        data: {target: 'alerts.input'})
      %span.icon.is-small.is-left
        %i.fas.fa-music
  .field
    = form.label :phone_number, class: :label
    %p.control.has-icons-left.has-icons-right
      = form.telephone_field(:phone_number,
                             id: :phone_number,
                             class: :input,
                             placeholder: '647-445-1141',
                             data: {target: 'alerts.input'})
      %span.icon.is-small.is-left
        %i.fas.fa-mobile-alt
  .field
    %p.control
      = form.submit 'Send Top Track', class: 'button is-dark'

app/views/welcome/_latest_release.html.haml
%article#latest-release-tile.tile.is-child.box
  .columns.is-desktop
    .column.is-one-quarter
      %figure.image.is-96x96
        %img{src: '', data: {target: 'artist-info.releaseImage'}}
    .column
      %p.title{data: {target: 'artist-info.releaseName'}}
      %p.subtitle Latest Release
  .content
    %strong Release Date:
    %span{data: {target: 'artist-info.releaseDate'}}
    %br
    %strong Release Type:
    %span{data: {target: 'artist-info.releaseType'}}

app/views/welcome/_related_artist_popularity.html.haml
%article#popularity-tile.tile.is-child.box
  %p.title Related Artist Popularity
  %p.subtitle Values range from 0 to 100
  .content
    = bar_chart([], id: 'popularity-chart')

app/views/welcome/index.html.haml
%section.hero.is-primary.is-bold
  .hero-body
    .container
      .columns.is-variable.is-6
        .column
          %h1.title
            Spotify Top Tracks
          %h2.subtitle
            Enter an artist. Provide a phone number. Find out their top Spotify track via text.
          %h2
            %strong.has-background-light
              %span.has-text-danger
                Note:
              %span.has-text-dark
                This is a demo app using a Twilio test account. Real text message will not be sent.
        .column
          = render partial: 'form'
        .column
          = render partial: 'alert_box'
%section#artist-section
  .container.is-fluid.is-invisible#artist-container{data: {target: 'artist-info.container'}}
    .tile.is-ancestor
      .tile.is-parent.is-5.is-vertical
        = render partial: 'artist_info'
        = render partial: 'latest_release'
      .tile.is-parent.is-7
        = render partial: 'related_artist_popularity'